AssingmentSmartHR/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AssingmentSmartHR/force-app/main/default/objects/Applicant__c/fields/Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Name__c</fullName>
    <label>Applicant Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

AssingmentSmartHR/force-app/main/default/objects/Offer__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

AssingmentSmartHR/force-app/main/default/objects/Offer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Review Requested</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

AssingmentSmartHR/force-app/main/default/classes/ScheduledJobOffer.cls
global class ScheduledJobOffer implements Schedulable{
    global void execute(SchedulableContext ctx){
        List<Contact> contacts = new List<Contact>();
        Set<ID> applicantIds = new Set<ID>();
        List<Offer__c> offers = [SELECT Status__c, Applicant__c FROM Offer__c WHERE Status__c = 'Accepted' LIMIT 200];
        for(Offer__c offer : offers){
            applicantIds.add(offer.Applicant__c);
        }
        List<Applicant__c> applicants = [SELECT Id, Applicant_Name__c, Phone__c, Email__c FROM Applicant__c WHERE Id in :applicantIds];
        for(Applicant__c applicant : applicants){
            Contact newContact = new Contact();
            String[] fullName = applicant.Applicant_Name__c.Split(' ');
            newContact.FirstName = fullName[0];            
            newContact.LastName = fullName[1];
            newContact.Phone = applicant.Phone__c;
            newContact.Email = applicant.Email__c;
            contacts.Add(newContact);
        }
        upsert contacts;
    }
}