AssingmentSmartHR/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AssingmentSmartHR/force-app/main/default/objects/Applicant__c/fields/Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Name__c</fullName>
    <label>Applicant Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

AssingmentSmartHR/force-app/main/default/objects/Offer__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

AssingmentSmartHR/force-app/main/default/objects/Offer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Review Requested</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

AssingmentSmartHR/force-app/main/default/classes/TestScheduledJobOffer.cls
@isTest
private class TestScheduledJobOffer {
    
    // Dummy CRON expression: midnight on March 15.
    // Because this is a test, job executes
    // immediately after Test.stopTest().
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    static testmethod void testScheduledJob() {
        
        Applicant__c applicant = new Applicant__c();
        applicant.Applicant_Name__c = 'Jose Lopez';
        applicant.Email__c = 'asds@asdsad.cl';
        applicant.Phone__c = '991987333';        
        insert applicant;
       
        List<Offer__c> offers = new List<Offer__c>();
        for (Integer i=0; i<10; i++) {
            Offer__c offer = new Offer__c(
                Applicant__c = applicant.Id,                
                Name = 'Test ' + i,
                Status__c = 'Accepted'                
            );
            offers.add(offer);
        }
        insert offers;

        
        Test.startTest();
        String jobId = System.schedule('Nightly Job', CRON_EXP, new ScheduledJobOffer());
        Test.stopTest();
        
        System.assertEquals(offers.size(), 10, 'Offers Created');
        
    }
}